# Generated by Django 5.1.3 on 2025-05-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemsPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=20)),
                ('snippet', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='problemsPage.problem')),
            ],
            options={
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
